// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: direct.proto

package rootlayerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentConnectRequest - Agent initiates connection
type AgentConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentAddress  string                 `protobuf:"bytes,1,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                              // Signature proving Agent identity
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // Agent client version
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // Connection timestamp (unix seconds, for signature freshness)
	RandomNonce   []byte                 `protobuf:"bytes,5,opt,name=random_nonce,json=randomNonce,proto3" json:"random_nonce,omitempty"`       // 32-byte random nonce (for signature uniqueness)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConnectRequest) Reset() {
	*x = AgentConnectRequest{}
	mi := &file_direct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConnectRequest) ProtoMessage() {}

func (x *AgentConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConnectRequest.ProtoReflect.Descriptor instead.
func (*AgentConnectRequest) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConnectRequest) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *AgentConnectRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AgentConnectRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AgentConnectRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentConnectRequest) GetRandomNonce() []byte {
	if x != nil {
		return x.RandomNonce
	}
	return nil
}

// DirectIntentPush - Relayer pushes Intent to Agent via stream
type DirectIntentPush struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IntentId              string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	SubnetId              string                 `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Requester             string                 `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	IntentType            string                 `protobuf:"bytes,4,opt,name=intent_type,json=intentType,proto3" json:"intent_type,omitempty"`
	Params                *IntentParams          `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	PaymentToken          string                 `protobuf:"bytes,6,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	Amount                string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Deadline              int64                  `protobuf:"varint,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	ChallengeEndTimestamp int64                  `protobuf:"varint,9,opt,name=challenge_end_timestamp,json=challengeEndTimestamp,proto3" json:"challenge_end_timestamp,omitempty"`
	ParamsHash            []byte                 `protobuf:"bytes,10,opt,name=params_hash,json=paramsHash,proto3" json:"params_hash,omitempty"`
	TargetAgentId         string                 `protobuf:"bytes,11,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DirectIntentPush) Reset() {
	*x = DirectIntentPush{}
	mi := &file_direct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectIntentPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectIntentPush) ProtoMessage() {}

func (x *DirectIntentPush) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectIntentPush.ProtoReflect.Descriptor instead.
func (*DirectIntentPush) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{1}
}

func (x *DirectIntentPush) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *DirectIntentPush) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *DirectIntentPush) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *DirectIntentPush) GetIntentType() string {
	if x != nil {
		return x.IntentType
	}
	return ""
}

func (x *DirectIntentPush) GetParams() *IntentParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DirectIntentPush) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *DirectIntentPush) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DirectIntentPush) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *DirectIntentPush) GetChallengeEndTimestamp() int64 {
	if x != nil {
		return x.ChallengeEndTimestamp
	}
	return 0
}

func (x *DirectIntentPush) GetParamsHash() []byte {
	if x != nil {
		return x.ParamsHash
	}
	return nil
}

func (x *DirectIntentPush) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

// HeartbeatRequest - Agent sends heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentAddress  string                 `protobuf:"bytes,1,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_direct_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DirectResultRequest - Agent submits execution result
type DirectResultRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IntentId       string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AgentAddress   string                 `protobuf:"bytes,2,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ResultData     []byte                 `protobuf:"bytes,4,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp      int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentSignature []byte                 `protobuf:"bytes,7,opt,name=agent_signature,json=agentSignature,proto3" json:"agent_signature,omitempty"` // Agent's signature over the result
	TargetAgentId  string                 `protobuf:"bytes,8,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	SubnetId       string                 `protobuf:"bytes,9,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectResultRequest) Reset() {
	*x = DirectResultRequest{}
	mi := &file_direct_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectResultRequest) ProtoMessage() {}

func (x *DirectResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectResultRequest.ProtoReflect.Descriptor instead.
func (*DirectResultRequest) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{3}
}

func (x *DirectResultRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *DirectResultRequest) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *DirectResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DirectResultRequest) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *DirectResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DirectResultRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DirectResultRequest) GetAgentSignature() []byte {
	if x != nil {
		return x.AgentSignature
	}
	return nil
}

func (x *DirectResultRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *DirectResultRequest) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

// DirectResultResponse - Response to Agent result submission
type DirectResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ResultHash    string                 `protobuf:"bytes,3,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"` // keccak256(result_data) for verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectResultResponse) Reset() {
	*x = DirectResultResponse{}
	mi := &file_direct_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectResultResponse) ProtoMessage() {}

func (x *DirectResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectResultResponse.ProtoReflect.Descriptor instead.
func (*DirectResultResponse) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{4}
}

func (x *DirectResultResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DirectResultResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DirectResultResponse) GetResultHash() string {
	if x != nil {
		return x.ResultHash
	}
	return ""
}

// SubmitDirectIntentRequest - User submits Direct Intent (aligned with SubmitIntentRequest)
type SubmitDirectIntentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-provided intent ID. A 32-byte 0x-prefixed hex value is recommended.
	IntentId string `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	// Target subnet identifier (32-byte 0x-prefixed hex string).
	SubnetId string `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// Requester wallet address (EIP-55 checksum expected).
	Requester string `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	// Settlement chain name, e.g. "base_sepolia".
	SettleChain string `protobuf:"bytes,4,opt,name=settle_chain,json=settleChain,proto3" json:"settle_chain,omitempty"`
	// Application-specific intent type, e.g. "book_flight".
	IntentType string `protobuf:"bytes,5,opt,name=intent_type,json=intentType,proto3" json:"intent_type,omitempty"`
	// Execution parameters. The on-chain params hash is keccak256(params).
	Params *IntentParams `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	// ERC-20 token address for payment (0x0 for native).
	PaymentToken string `protobuf:"bytes,7,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	// Payment amount as uint256 decimal string.
	Amount string `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`
	// Execution deadline (unix seconds).
	Deadline int64 `protobuf:"varint,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// User signature covering canonical intent content (EIP-191).
	Signature []byte `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	// Target agent address for Direct Mode execution.
	TargetAgent string `protobuf:"bytes,11,opt,name=target_agent,json=targetAgent,proto3" json:"target_agent,omitempty"`
	// ERC-8004 agent id (tokenId) for routing.
	TargetAgentId string `protobuf:"bytes,12,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDirectIntentRequest) Reset() {
	*x = SubmitDirectIntentRequest{}
	mi := &file_direct_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDirectIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDirectIntentRequest) ProtoMessage() {}

func (x *SubmitDirectIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDirectIntentRequest.ProtoReflect.Descriptor instead.
func (*SubmitDirectIntentRequest) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitDirectIntentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetSettleChain() string {
	if x != nil {
		return x.SettleChain
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetIntentType() string {
	if x != nil {
		return x.IntentType
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetParams() *IntentParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SubmitDirectIntentRequest) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *SubmitDirectIntentRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SubmitDirectIntentRequest) GetTargetAgent() string {
	if x != nil {
		return x.TargetAgent
	}
	return ""
}

func (x *SubmitDirectIntentRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

// SubmitDirectIntentResponse - Response to user submission (sync mode only)
type SubmitDirectIntentResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Ok       bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg      string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	IntentId string                 `protobuf:"bytes,3,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	// Agent execution result (returned within 30s timeout)
	Result *DirectResult `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	// keccak256(params) used by on-chain verification
	ParamsHash []byte `protobuf:"bytes,5,opt,name=params_hash,json=paramsHash,proto3" json:"params_hash,omitempty"`
	// Current intent status
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDirectIntentResponse) Reset() {
	*x = SubmitDirectIntentResponse{}
	mi := &file_direct_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDirectIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDirectIntentResponse) ProtoMessage() {}

func (x *SubmitDirectIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDirectIntentResponse.ProtoReflect.Descriptor instead.
func (*SubmitDirectIntentResponse) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitDirectIntentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitDirectIntentResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SubmitDirectIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *SubmitDirectIntentResponse) GetResult() *DirectResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SubmitDirectIntentResponse) GetParamsHash() []byte {
	if x != nil {
		return x.ParamsHash
	}
	return nil
}

func (x *SubmitDirectIntentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DirectResult - Agent execution result (embedded in response)
type DirectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AgentAddress  string                 `protobuf:"bytes,2,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,4,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	ResultHash    string                 `protobuf:"bytes,5,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TargetAgentId string                 `protobuf:"bytes,8,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	SubnetId      string                 `protobuf:"bytes,9,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectResult) Reset() {
	*x = DirectResult{}
	mi := &file_direct_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectResult) ProtoMessage() {}

func (x *DirectResult) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectResult.ProtoReflect.Descriptor instead.
func (*DirectResult) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{7}
}

func (x *DirectResult) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *DirectResult) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *DirectResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DirectResult) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *DirectResult) GetResultHash() string {
	if x != nil {
		return x.ResultHash
	}
	return ""
}

func (x *DirectResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DirectResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DirectResult) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *DirectResult) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

// GetDirectResultRequest - User queries result
type GetDirectResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectResultRequest) Reset() {
	*x = GetDirectResultRequest{}
	mi := &file_direct_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectResultRequest) ProtoMessage() {}

func (x *GetDirectResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectResultRequest.ProtoReflect.Descriptor instead.
func (*GetDirectResultRequest) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{8}
}

func (x *GetDirectResultRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

// DirectResultDetail - Full result details including metadata
type DirectResultDetail struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IntentId              string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AgentAddress          string                 `protobuf:"bytes,2,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	Success               bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ResultData            []byte                 `protobuf:"bytes,4,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	ResultHash            string                 `protobuf:"bytes,5,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp             int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResultReceived        bool                   `protobuf:"varint,8,opt,name=result_received,json=resultReceived,proto3" json:"result_received,omitempty"`
	ReceivedAt            int64                  `protobuf:"varint,9,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	ChallengeEndTimestamp int64                  `protobuf:"varint,10,opt,name=challenge_end_timestamp,json=challengeEndTimestamp,proto3" json:"challenge_end_timestamp,omitempty"`
	Disputed              bool                   `protobuf:"varint,11,opt,name=disputed,proto3" json:"disputed,omitempty"`
	CurrentStatus         string                 `protobuf:"bytes,12,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	TargetAgentId         string                 `protobuf:"bytes,13,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	SubnetId              string                 `protobuf:"bytes,14,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DirectResultDetail) Reset() {
	*x = DirectResultDetail{}
	mi := &file_direct_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectResultDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectResultDetail) ProtoMessage() {}

func (x *DirectResultDetail) ProtoReflect() protoreflect.Message {
	mi := &file_direct_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectResultDetail.ProtoReflect.Descriptor instead.
func (*DirectResultDetail) Descriptor() ([]byte, []int) {
	return file_direct_proto_rawDescGZIP(), []int{9}
}

func (x *DirectResultDetail) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *DirectResultDetail) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *DirectResultDetail) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DirectResultDetail) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *DirectResultDetail) GetResultHash() string {
	if x != nil {
		return x.ResultHash
	}
	return ""
}

func (x *DirectResultDetail) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DirectResultDetail) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DirectResultDetail) GetResultReceived() bool {
	if x != nil {
		return x.ResultReceived
	}
	return false
}

func (x *DirectResultDetail) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *DirectResultDetail) GetChallengeEndTimestamp() int64 {
	if x != nil {
		return x.ChallengeEndTimestamp
	}
	return 0
}

func (x *DirectResultDetail) GetDisputed() bool {
	if x != nil {
		return x.Disputed
	}
	return false
}

func (x *DirectResultDetail) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *DirectResultDetail) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *DirectResultDetail) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

var File_direct_proto protoreflect.FileDescriptor

const file_direct_proto_rawDesc = "" +
	"\n" +
	"\fdirect.proto\x12\frootlayer.v1\x1a\fintent.proto\"\xc0\x01\n" +
	"\x13AgentConnectRequest\x12#\n" +
	"\ragent_address\x18\x01 \x01(\tR\fagentAddress\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12!\n" +
	"\frandom_nonce\x18\x05 \x01(\fR\vrandomNonce\"\x99\x03\n" +
	"\x10DirectIntentPush\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x1b\n" +
	"\tsubnet_id\x18\x02 \x01(\tR\bsubnetId\x12\x1c\n" +
	"\trequester\x18\x03 \x01(\tR\trequester\x12\x1f\n" +
	"\vintent_type\x18\x04 \x01(\tR\n" +
	"intentType\x122\n" +
	"\x06params\x18\x05 \x01(\v2\x1a.rootlayer.v1.IntentParamsR\x06params\x12#\n" +
	"\rpayment_token\x18\x06 \x01(\tR\fpaymentToken\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12\x1a\n" +
	"\bdeadline\x18\b \x01(\x03R\bdeadline\x126\n" +
	"\x17challenge_end_timestamp\x18\t \x01(\x03R\x15challengeEndTimestamp\x12\x1f\n" +
	"\vparams_hash\x18\n" +
	" \x01(\fR\n" +
	"paramsHash\x12&\n" +
	"\x0ftarget_agent_id\x18\v \x01(\tR\rtargetAgentId\"U\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\ragent_address\x18\x01 \x01(\tR\fagentAddress\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xc3\x02\n" +
	"\x13DirectResultRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12#\n" +
	"\ragent_address\x18\x02 \x01(\tR\fagentAddress\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_data\x18\x04 \x01(\fR\n" +
	"resultData\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fagent_signature\x18\a \x01(\fR\x0eagentSignature\x12&\n" +
	"\x0ftarget_agent_id\x18\b \x01(\tR\rtargetAgentId\x12\x1b\n" +
	"\tsubnet_id\x18\t \x01(\tR\bsubnetId\"Y\n" +
	"\x14DirectResultResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vresult_hash\x18\x03 \x01(\tR\n" +
	"resultHash\"\xad\x03\n" +
	"\x19SubmitDirectIntentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x1b\n" +
	"\tsubnet_id\x18\x02 \x01(\tR\bsubnetId\x12\x1c\n" +
	"\trequester\x18\x03 \x01(\tR\trequester\x12!\n" +
	"\fsettle_chain\x18\x04 \x01(\tR\vsettleChain\x12\x1f\n" +
	"\vintent_type\x18\x05 \x01(\tR\n" +
	"intentType\x122\n" +
	"\x06params\x18\x06 \x01(\v2\x1a.rootlayer.v1.IntentParamsR\x06params\x12#\n" +
	"\rpayment_token\x18\a \x01(\tR\fpaymentToken\x12\x16\n" +
	"\x06amount\x18\b \x01(\tR\x06amount\x12\x1a\n" +
	"\bdeadline\x18\t \x01(\x03R\bdeadline\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\x12!\n" +
	"\ftarget_agent\x18\v \x01(\tR\vtargetAgent\x12&\n" +
	"\x0ftarget_agent_id\x18\f \x01(\tR\rtargetAgentId\"\xc8\x01\n" +
	"\x1aSubmitDirectIntentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tintent_id\x18\x03 \x01(\tR\bintentId\x122\n" +
	"\x06result\x18\x04 \x01(\v2\x1a.rootlayer.v1.DirectResultR\x06result\x12\x1f\n" +
	"\vparams_hash\x18\x05 \x01(\fR\n" +
	"paramsHash\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xb4\x02\n" +
	"\fDirectResult\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12#\n" +
	"\ragent_address\x18\x02 \x01(\tR\fagentAddress\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_data\x18\x04 \x01(\fR\n" +
	"resultData\x12\x1f\n" +
	"\vresult_hash\x18\x05 \x01(\tR\n" +
	"resultHash\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12&\n" +
	"\x0ftarget_agent_id\x18\b \x01(\tR\rtargetAgentId\x12\x1b\n" +
	"\tsubnet_id\x18\t \x01(\tR\bsubnetId\"5\n" +
	"\x16GetDirectResultRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\"\xff\x03\n" +
	"\x12DirectResultDetail\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12#\n" +
	"\ragent_address\x18\x02 \x01(\tR\fagentAddress\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_data\x18\x04 \x01(\fR\n" +
	"resultData\x12\x1f\n" +
	"\vresult_hash\x18\x05 \x01(\tR\n" +
	"resultHash\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fresult_received\x18\b \x01(\bR\x0eresultReceived\x12\x1f\n" +
	"\vreceived_at\x18\t \x01(\x03R\n" +
	"receivedAt\x126\n" +
	"\x17challenge_end_timestamp\x18\n" +
	" \x01(\x03R\x15challengeEndTimestamp\x12\x1a\n" +
	"\bdisputed\x18\v \x01(\bR\bdisputed\x12%\n" +
	"\x0ecurrent_status\x18\f \x01(\tR\rcurrentStatus\x12&\n" +
	"\x0ftarget_agent_id\x18\r \x01(\tR\rtargetAgentId\x12\x1b\n" +
	"\tsubnet_id\x18\x0e \x01(\tR\bsubnetIdBBZ@github.com/PIN-AI/pin-protocol-proto/rootlayer/proto;rootlayerv1b\x06proto3"

var (
	file_direct_proto_rawDescOnce sync.Once
	file_direct_proto_rawDescData []byte
)

func file_direct_proto_rawDescGZIP() []byte {
	file_direct_proto_rawDescOnce.Do(func() {
		file_direct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_direct_proto_rawDesc), len(file_direct_proto_rawDesc)))
	})
	return file_direct_proto_rawDescData
}

var file_direct_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_direct_proto_goTypes = []any{
	(*AgentConnectRequest)(nil),        // 0: rootlayer.v1.AgentConnectRequest
	(*DirectIntentPush)(nil),           // 1: rootlayer.v1.DirectIntentPush
	(*HeartbeatRequest)(nil),           // 2: rootlayer.v1.HeartbeatRequest
	(*DirectResultRequest)(nil),        // 3: rootlayer.v1.DirectResultRequest
	(*DirectResultResponse)(nil),       // 4: rootlayer.v1.DirectResultResponse
	(*SubmitDirectIntentRequest)(nil),  // 5: rootlayer.v1.SubmitDirectIntentRequest
	(*SubmitDirectIntentResponse)(nil), // 6: rootlayer.v1.SubmitDirectIntentResponse
	(*DirectResult)(nil),               // 7: rootlayer.v1.DirectResult
	(*GetDirectResultRequest)(nil),     // 8: rootlayer.v1.GetDirectResultRequest
	(*DirectResultDetail)(nil),         // 9: rootlayer.v1.DirectResultDetail
	(*IntentParams)(nil),               // 10: rootlayer.v1.IntentParams
}
var file_direct_proto_depIdxs = []int32{
	10, // 0: rootlayer.v1.DirectIntentPush.params:type_name -> rootlayer.v1.IntentParams
	10, // 1: rootlayer.v1.SubmitDirectIntentRequest.params:type_name -> rootlayer.v1.IntentParams
	7,  // 2: rootlayer.v1.SubmitDirectIntentResponse.result:type_name -> rootlayer.v1.DirectResult
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_direct_proto_init() }
func file_direct_proto_init() {
	if File_direct_proto != nil {
		return
	}
	file_intent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_direct_proto_rawDesc), len(file_direct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_direct_proto_goTypes,
		DependencyIndexes: file_direct_proto_depIdxs,
		MessageInfos:      file_direct_proto_msgTypes,
	}.Build()
	File_direct_proto = out.File
	file_direct_proto_goTypes = nil
	file_direct_proto_depIdxs = nil
}
