// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: error_reason.proto

package rootlayerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Intent-specific error codes
// Error code ranges:
// 4000-4999: Request validation errors (Bad Request)
// 5000-5999: Business logic errors (Unprocessable Entity)
// 6000-6999: Resource limit errors (Conflict/Too Many Requests)
// 7000-7999: System errors (Internal Server Error)
type IntentErrorReason int32

const (
	// Success status
	IntentErrorReason_INTENT_SUCCESS IntentErrorReason = 0
	// Intent basic validation errors 4000-4099
	IntentErrorReason_INTENT_INVALID_REQUEST          IntentErrorReason = 4000 // Request format invalid
	IntentErrorReason_INTENT_INVALID_PARAMETERS       IntentErrorReason = 4001 // Parameters invalid
	IntentErrorReason_INTENT_MISSING_REQUIRED_FIELD   IntentErrorReason = 4002 // Missing required field
	IntentErrorReason_INTENT_INVALID_FIELD_FORMAT     IntentErrorReason = 4003 // Field format error
	IntentErrorReason_INTENT_INVALID_UUID             IntentErrorReason = 4004 // UUID format error
	IntentErrorReason_INTENT_INVALID_ADDRESS          IntentErrorReason = 4005 // Ethereum address format error
	IntentErrorReason_INTENT_INVALID_TIMESTAMP        IntentErrorReason = 4006 // Timestamp format error
	IntentErrorReason_INTENT_INVALID_SIGNATURE_FORMAT IntentErrorReason = 4007 // Signature format error
	IntentErrorReason_INTENT_INVALID_CHAIN_ID         IntentErrorReason = 4008 // Chain ID invalid
	IntentErrorReason_INTENT_INVALID_TOKEN_ADDRESS    IntentErrorReason = 4009 // Token address invalid
	// Intent business validation errors 4100-4199
	IntentErrorReason_INTENT_EXPIRED_DEADLINE    IntentErrorReason = 4100 // Deadline expired
	IntentErrorReason_INTENT_INVALID_BUDGET      IntentErrorReason = 4101 // Budget amount invalid
	IntentErrorReason_INTENT_BUDGET_TOO_LOW      IntentErrorReason = 4102 // Budget amount too low
	IntentErrorReason_INTENT_BUDGET_TOO_HIGH     IntentErrorReason = 4103 // Budget amount too high
	IntentErrorReason_INTENT_DEADLINE_TOO_EARLY  IntentErrorReason = 4104 // Deadline too early
	IntentErrorReason_INTENT_DEADLINE_TOO_LATE   IntentErrorReason = 4105 // Deadline too late
	IntentErrorReason_INTENT_INVALID_INTENT_TYPE IntentErrorReason = 4106 // Intent type invalid
	IntentErrorReason_INTENT_UNSUPPORTED_CHAIN   IntentErrorReason = 4107 // Unsupported chain
	IntentErrorReason_INTENT_UNSUPPORTED_TOKEN   IntentErrorReason = 4108 // Unsupported token
	IntentErrorReason_INTENT_PARAMS_TOO_LARGE    IntentErrorReason = 4109 // Parameters data too large
	// Signature validation errors 4200-4299
	IntentErrorReason_INTENT_SIGNATURE_VERIFICATION_FAILED IntentErrorReason = 4200 // Signature verification failed
	IntentErrorReason_INTENT_INVALID_SIGNATURE             IntentErrorReason = 4201 // Signature invalid
	IntentErrorReason_INTENT_SIGNATURE_MISMATCH            IntentErrorReason = 4202 // Signature mismatch
	IntentErrorReason_INTENT_SIGNER_MISMATCH               IntentErrorReason = 4203 // Signer mismatch
	IntentErrorReason_INTENT_SIGNATURE_REPLAY              IntentErrorReason = 4204 // Signature replay attack
	IntentErrorReason_INTENT_SIGNATURE_EXPIRED             IntentErrorReason = 4205 // Signature expired
	IntentErrorReason_INTENT_INVALID_SIGNATURE_TYPE        IntentErrorReason = 4206 // Signature type invalid
	IntentErrorReason_INTENT_EIP712_VALIDATION_FAILED      IntentErrorReason = 4207 // EIP-712 validation failed
	IntentErrorReason_INTENT_EIP191_VALIDATION_FAILED      IntentErrorReason = 4208 // EIP-191 validation failed
	// Subnet validation errors 4300-4399
	IntentErrorReason_INTENT_SUBNET_NOT_FOUND               IntentErrorReason = 4300 // Subnet not found
	IntentErrorReason_INTENT_SUBNET_INACTIVE                IntentErrorReason = 4301 // Subnet inactive
	IntentErrorReason_INTENT_SUBNET_OVERLOADED              IntentErrorReason = 4302 // Subnet overloaded
	IntentErrorReason_INTENT_SUBNET_UNSUPPORTED             IntentErrorReason = 4303 // Subnet doesn't support this intent type
	IntentErrorReason_INTENT_SUBNET_INSUFFICIENT_VALIDATORS IntentErrorReason = 4304 // Subnet insufficient validators
	IntentErrorReason_INTENT_SUBNET_MAINTENANCE             IntentErrorReason = 4305 // Subnet under maintenance
	// Intent status related errors 5000-5099
	IntentErrorReason_INTENT_ALREADY_EXISTS             IntentErrorReason = 5000 // Intent already exists
	IntentErrorReason_INTENT_NOT_FOUND                  IntentErrorReason = 5001 // Intent not found
	IntentErrorReason_INTENT_INVALID_STATUS             IntentErrorReason = 5002 // Intent status invalid
	IntentErrorReason_INTENT_STATUS_TRANSITION_INVALID  IntentErrorReason = 5003 // Status transition invalid
	IntentErrorReason_INTENT_ALREADY_PROCESSED          IntentErrorReason = 5004 // Intent already processed
	IntentErrorReason_INTENT_ALREADY_EXPIRED            IntentErrorReason = 5005 // Intent already expired
	IntentErrorReason_INTENT_ALREADY_COMPLETED          IntentErrorReason = 5006 // Intent already completed
	IntentErrorReason_INTENT_ALREADY_FAILED             IntentErrorReason = 5007 // Intent already failed
	IntentErrorReason_INTENT_CANNOT_CANCEL              IntentErrorReason = 5008 // Cannot cancel intent
	IntentErrorReason_INTENT_PROCESSING_DEADLINE_PASSED IntentErrorReason = 5009 // Processing deadline passed
	// Bidding related errors 5100-5199
	IntentErrorReason_INTENT_BIDDING_NOT_STARTED  IntentErrorReason = 5100 // Bidding not started
	IntentErrorReason_INTENT_BIDDING_ENDED        IntentErrorReason = 5101 // Bidding ended
	IntentErrorReason_INTENT_NO_VALID_BIDS        IntentErrorReason = 5102 // No valid bids
	IntentErrorReason_INTENT_BID_TOO_LOW          IntentErrorReason = 5103 // Bid too low
	IntentErrorReason_INTENT_BID_TOO_HIGH         IntentErrorReason = 5104 // Bid too high
	IntentErrorReason_INTENT_BIDDER_NOT_QUALIFIED IntentErrorReason = 5105 // Bidder not qualified
	IntentErrorReason_INTENT_BID_ALREADY_EXISTS   IntentErrorReason = 5106 // Bid already exists
	IntentErrorReason_INTENT_INSUFFICIENT_STAKE   IntentErrorReason = 5107 // Insufficient stake
	// Execution related errors 5200-5299
	IntentErrorReason_INTENT_EXECUTION_NOT_STARTED      IntentErrorReason = 5200 // Execution not started
	IntentErrorReason_INTENT_EXECUTION_FAILED           IntentErrorReason = 5201 // Execution failed
	IntentErrorReason_INTENT_EXECUTION_TIMEOUT          IntentErrorReason = 5202 // Execution timeout
	IntentErrorReason_INTENT_EXECUTION_REJECTED         IntentErrorReason = 5203 // Execution rejected
	IntentErrorReason_INTENT_EXECUTION_PARAMS_INVALID   IntentErrorReason = 5204 // Execution parameters invalid
	IntentErrorReason_INTENT_EXECUTION_INSUFFICIENT_GAS IntentErrorReason = 5205 // Insufficient gas
	IntentErrorReason_INTENT_EXECUTION_NETWORK_ERROR    IntentErrorReason = 5206 // Network error
	IntentErrorReason_INTENT_EXECUTION_CONTRACT_ERROR   IntentErrorReason = 5207 // Contract execution error
	// Validation related errors 5300-5399
	IntentErrorReason_INTENT_VALIDATION_PENDING           IntentErrorReason = 5300 // Validation pending
	IntentErrorReason_INTENT_VALIDATION_FAILED            IntentErrorReason = 5301 // Validation failed
	IntentErrorReason_INTENT_VALIDATION_TIMEOUT           IntentErrorReason = 5302 // Validation timeout
	IntentErrorReason_INTENT_INSUFFICIENT_VALIDATORS      IntentErrorReason = 5303 // Insufficient validators
	IntentErrorReason_INTENT_VALIDATION_CONSENSUS_FAILED  IntentErrorReason = 5304 // Validation consensus failed
	IntentErrorReason_INTENT_VALIDATION_SIGNATURE_INVALID IntentErrorReason = 5305 // Validation signature invalid
	// System capacity limits 6000-6099
	IntentErrorReason_INTENT_RATE_LIMIT_EXCEEDED      IntentErrorReason = 6000 // Rate limit
	IntentErrorReason_INTENT_QUEUE_FULL               IntentErrorReason = 6001 // Queue full
	IntentErrorReason_INTENT_MAX_CONCURRENT_LIMIT     IntentErrorReason = 6002 // Concurrent limit
	IntentErrorReason_INTENT_DAILY_LIMIT_EXCEEDED     IntentErrorReason = 6003 // Daily limit exceeded
	IntentErrorReason_INTENT_USER_QUOTA_EXCEEDED      IntentErrorReason = 6004 // User quota exceeded
	IntentErrorReason_INTENT_SUBNET_CAPACITY_EXCEEDED IntentErrorReason = 6005 // Subnet capacity exceeded
	IntentErrorReason_INTENT_GLOBAL_CAPACITY_EXCEEDED IntentErrorReason = 6006 // Global capacity exceeded
	// Resource conflicts 6100-6199
	IntentErrorReason_INTENT_RESOURCE_LOCKED         IntentErrorReason = 6100 // Resource locked
	IntentErrorReason_INTENT_RESOURCE_BUSY           IntentErrorReason = 6101 // Resource busy
	IntentErrorReason_INTENT_DEPENDENCY_CONFLICT     IntentErrorReason = 6102 // Dependency conflict
	IntentErrorReason_INTENT_CONCURRENT_MODIFICATION IntentErrorReason = 6103 // Concurrent modification
	IntentErrorReason_INTENT_VERSION_CONFLICT        IntentErrorReason = 6104 // Version conflict
	// Database errors 7000-7099
	IntentErrorReason_INTENT_DATABASE_ERROR                IntentErrorReason = 7000 // Database error
	IntentErrorReason_INTENT_DATABASE_CONNECTION_FAILED    IntentErrorReason = 7001 // Database connection failed
	IntentErrorReason_INTENT_DATABASE_TIMEOUT              IntentErrorReason = 7002 // Database timeout
	IntentErrorReason_INTENT_DATABASE_CONSTRAINT_VIOLATION IntentErrorReason = 7003 // Database constraint violation
	IntentErrorReason_INTENT_DATABASE_TRANSACTION_FAILED   IntentErrorReason = 7004 // Transaction failed
	IntentErrorReason_INTENT_DATABASE_MIGRATION_ERROR      IntentErrorReason = 7005 // Migration error
	// Cache errors 7100-7199
	IntentErrorReason_INTENT_CACHE_ERROR             IntentErrorReason = 7100 // Cache error
	IntentErrorReason_INTENT_CACHE_CONNECTION_FAILED IntentErrorReason = 7101 // Cache connection failed
	IntentErrorReason_INTENT_CACHE_TIMEOUT           IntentErrorReason = 7102 // Cache timeout
	IntentErrorReason_INTENT_CACHE_EVICTION_ERROR    IntentErrorReason = 7103 // Cache eviction error
	// Blockchain integration errors 7200-7299
	IntentErrorReason_INTENT_BLOCKCHAIN_ERROR                 IntentErrorReason = 7200 // Blockchain error
	IntentErrorReason_INTENT_BLOCKCHAIN_CONNECTION_FAILED     IntentErrorReason = 7201 // Blockchain connection failed
	IntentErrorReason_INTENT_BLOCKCHAIN_TIMEOUT               IntentErrorReason = 7202 // Blockchain timeout
	IntentErrorReason_INTENT_BLOCKCHAIN_TRANSACTION_FAILED    IntentErrorReason = 7203 // Transaction failed
	IntentErrorReason_INTENT_BLOCKCHAIN_GAS_ESTIMATION_FAILED IntentErrorReason = 7204 // Gas estimation failed
	IntentErrorReason_INTENT_BLOCKCHAIN_INSUFFICIENT_BALANCE  IntentErrorReason = 7205 // Insufficient balance
	IntentErrorReason_INTENT_BLOCKCHAIN_NONCE_ERROR           IntentErrorReason = 7206 // Nonce error
	IntentErrorReason_INTENT_BLOCKCHAIN_NETWORK_CONGESTION    IntentErrorReason = 7207 // Network congestion
	// gRPC/Network errors 7300-7399
	IntentErrorReason_INTENT_GRPC_ERROR             IntentErrorReason = 7300 // gRPC error
	IntentErrorReason_INTENT_GRPC_CONNECTION_FAILED IntentErrorReason = 7301 // gRPC connection failed
	IntentErrorReason_INTENT_GRPC_TIMEOUT           IntentErrorReason = 7302 // gRPC timeout
	IntentErrorReason_INTENT_GRPC_UNAVAILABLE       IntentErrorReason = 7303 // gRPC service unavailable
	IntentErrorReason_INTENT_NETWORK_ERROR          IntentErrorReason = 7304 // Network error
	IntentErrorReason_INTENT_NETWORK_TIMEOUT        IntentErrorReason = 7305 // Network timeout
	// System internal errors 7400-7499
	IntentErrorReason_INTENT_INTERNAL_ERROR        IntentErrorReason = 7400 // Internal error
	IntentErrorReason_INTENT_CONFIGURATION_ERROR   IntentErrorReason = 7401 // Configuration error
	IntentErrorReason_INTENT_SERVICE_UNAVAILABLE   IntentErrorReason = 7402 // Service unavailable
	IntentErrorReason_INTENT_MEMORY_ERROR          IntentErrorReason = 7403 // Memory error
	IntentErrorReason_INTENT_FILE_SYSTEM_ERROR     IntentErrorReason = 7404 // File system error
	IntentErrorReason_INTENT_SERIALIZATION_ERROR   IntentErrorReason = 7405 // Serialization error
	IntentErrorReason_INTENT_DESERIALIZATION_ERROR IntentErrorReason = 7406 // Deserialization error
	IntentErrorReason_INTENT_ENCRYPTION_ERROR      IntentErrorReason = 7407 // Encryption error
	IntentErrorReason_INTENT_DECRYPTION_ERROR      IntentErrorReason = 7408 // Decryption error
	// Third-party service errors 7500-7599
	IntentErrorReason_INTENT_EXTERNAL_SERVICE_ERROR       IntentErrorReason = 7500 // External service error
	IntentErrorReason_INTENT_EXTERNAL_SERVICE_TIMEOUT     IntentErrorReason = 7501 // External service timeout
	IntentErrorReason_INTENT_EXTERNAL_SERVICE_UNAVAILABLE IntentErrorReason = 7502 // External service unavailable
	IntentErrorReason_INTENT_API_RATE_LIMITED             IntentErrorReason = 7503 // External API rate limited
	IntentErrorReason_INTENT_API_AUTHENTICATION_FAILED    IntentErrorReason = 7504 // External API authentication failed
)

// Enum value maps for IntentErrorReason.
var (
	IntentErrorReason_name = map[int32]string{
		0:    "INTENT_SUCCESS",
		4000: "INTENT_INVALID_REQUEST",
		4001: "INTENT_INVALID_PARAMETERS",
		4002: "INTENT_MISSING_REQUIRED_FIELD",
		4003: "INTENT_INVALID_FIELD_FORMAT",
		4004: "INTENT_INVALID_UUID",
		4005: "INTENT_INVALID_ADDRESS",
		4006: "INTENT_INVALID_TIMESTAMP",
		4007: "INTENT_INVALID_SIGNATURE_FORMAT",
		4008: "INTENT_INVALID_CHAIN_ID",
		4009: "INTENT_INVALID_TOKEN_ADDRESS",
		4100: "INTENT_EXPIRED_DEADLINE",
		4101: "INTENT_INVALID_BUDGET",
		4102: "INTENT_BUDGET_TOO_LOW",
		4103: "INTENT_BUDGET_TOO_HIGH",
		4104: "INTENT_DEADLINE_TOO_EARLY",
		4105: "INTENT_DEADLINE_TOO_LATE",
		4106: "INTENT_INVALID_INTENT_TYPE",
		4107: "INTENT_UNSUPPORTED_CHAIN",
		4108: "INTENT_UNSUPPORTED_TOKEN",
		4109: "INTENT_PARAMS_TOO_LARGE",
		4200: "INTENT_SIGNATURE_VERIFICATION_FAILED",
		4201: "INTENT_INVALID_SIGNATURE",
		4202: "INTENT_SIGNATURE_MISMATCH",
		4203: "INTENT_SIGNER_MISMATCH",
		4204: "INTENT_SIGNATURE_REPLAY",
		4205: "INTENT_SIGNATURE_EXPIRED",
		4206: "INTENT_INVALID_SIGNATURE_TYPE",
		4207: "INTENT_EIP712_VALIDATION_FAILED",
		4208: "INTENT_EIP191_VALIDATION_FAILED",
		4300: "INTENT_SUBNET_NOT_FOUND",
		4301: "INTENT_SUBNET_INACTIVE",
		4302: "INTENT_SUBNET_OVERLOADED",
		4303: "INTENT_SUBNET_UNSUPPORTED",
		4304: "INTENT_SUBNET_INSUFFICIENT_VALIDATORS",
		4305: "INTENT_SUBNET_MAINTENANCE",
		5000: "INTENT_ALREADY_EXISTS",
		5001: "INTENT_NOT_FOUND",
		5002: "INTENT_INVALID_STATUS",
		5003: "INTENT_STATUS_TRANSITION_INVALID",
		5004: "INTENT_ALREADY_PROCESSED",
		5005: "INTENT_ALREADY_EXPIRED",
		5006: "INTENT_ALREADY_COMPLETED",
		5007: "INTENT_ALREADY_FAILED",
		5008: "INTENT_CANNOT_CANCEL",
		5009: "INTENT_PROCESSING_DEADLINE_PASSED",
		5100: "INTENT_BIDDING_NOT_STARTED",
		5101: "INTENT_BIDDING_ENDED",
		5102: "INTENT_NO_VALID_BIDS",
		5103: "INTENT_BID_TOO_LOW",
		5104: "INTENT_BID_TOO_HIGH",
		5105: "INTENT_BIDDER_NOT_QUALIFIED",
		5106: "INTENT_BID_ALREADY_EXISTS",
		5107: "INTENT_INSUFFICIENT_STAKE",
		5200: "INTENT_EXECUTION_NOT_STARTED",
		5201: "INTENT_EXECUTION_FAILED",
		5202: "INTENT_EXECUTION_TIMEOUT",
		5203: "INTENT_EXECUTION_REJECTED",
		5204: "INTENT_EXECUTION_PARAMS_INVALID",
		5205: "INTENT_EXECUTION_INSUFFICIENT_GAS",
		5206: "INTENT_EXECUTION_NETWORK_ERROR",
		5207: "INTENT_EXECUTION_CONTRACT_ERROR",
		5300: "INTENT_VALIDATION_PENDING",
		5301: "INTENT_VALIDATION_FAILED",
		5302: "INTENT_VALIDATION_TIMEOUT",
		5303: "INTENT_INSUFFICIENT_VALIDATORS",
		5304: "INTENT_VALIDATION_CONSENSUS_FAILED",
		5305: "INTENT_VALIDATION_SIGNATURE_INVALID",
		6000: "INTENT_RATE_LIMIT_EXCEEDED",
		6001: "INTENT_QUEUE_FULL",
		6002: "INTENT_MAX_CONCURRENT_LIMIT",
		6003: "INTENT_DAILY_LIMIT_EXCEEDED",
		6004: "INTENT_USER_QUOTA_EXCEEDED",
		6005: "INTENT_SUBNET_CAPACITY_EXCEEDED",
		6006: "INTENT_GLOBAL_CAPACITY_EXCEEDED",
		6100: "INTENT_RESOURCE_LOCKED",
		6101: "INTENT_RESOURCE_BUSY",
		6102: "INTENT_DEPENDENCY_CONFLICT",
		6103: "INTENT_CONCURRENT_MODIFICATION",
		6104: "INTENT_VERSION_CONFLICT",
		7000: "INTENT_DATABASE_ERROR",
		7001: "INTENT_DATABASE_CONNECTION_FAILED",
		7002: "INTENT_DATABASE_TIMEOUT",
		7003: "INTENT_DATABASE_CONSTRAINT_VIOLATION",
		7004: "INTENT_DATABASE_TRANSACTION_FAILED",
		7005: "INTENT_DATABASE_MIGRATION_ERROR",
		7100: "INTENT_CACHE_ERROR",
		7101: "INTENT_CACHE_CONNECTION_FAILED",
		7102: "INTENT_CACHE_TIMEOUT",
		7103: "INTENT_CACHE_EVICTION_ERROR",
		7200: "INTENT_BLOCKCHAIN_ERROR",
		7201: "INTENT_BLOCKCHAIN_CONNECTION_FAILED",
		7202: "INTENT_BLOCKCHAIN_TIMEOUT",
		7203: "INTENT_BLOCKCHAIN_TRANSACTION_FAILED",
		7204: "INTENT_BLOCKCHAIN_GAS_ESTIMATION_FAILED",
		7205: "INTENT_BLOCKCHAIN_INSUFFICIENT_BALANCE",
		7206: "INTENT_BLOCKCHAIN_NONCE_ERROR",
		7207: "INTENT_BLOCKCHAIN_NETWORK_CONGESTION",
		7300: "INTENT_GRPC_ERROR",
		7301: "INTENT_GRPC_CONNECTION_FAILED",
		7302: "INTENT_GRPC_TIMEOUT",
		7303: "INTENT_GRPC_UNAVAILABLE",
		7304: "INTENT_NETWORK_ERROR",
		7305: "INTENT_NETWORK_TIMEOUT",
		7400: "INTENT_INTERNAL_ERROR",
		7401: "INTENT_CONFIGURATION_ERROR",
		7402: "INTENT_SERVICE_UNAVAILABLE",
		7403: "INTENT_MEMORY_ERROR",
		7404: "INTENT_FILE_SYSTEM_ERROR",
		7405: "INTENT_SERIALIZATION_ERROR",
		7406: "INTENT_DESERIALIZATION_ERROR",
		7407: "INTENT_ENCRYPTION_ERROR",
		7408: "INTENT_DECRYPTION_ERROR",
		7500: "INTENT_EXTERNAL_SERVICE_ERROR",
		7501: "INTENT_EXTERNAL_SERVICE_TIMEOUT",
		7502: "INTENT_EXTERNAL_SERVICE_UNAVAILABLE",
		7503: "INTENT_API_RATE_LIMITED",
		7504: "INTENT_API_AUTHENTICATION_FAILED",
	}
	IntentErrorReason_value = map[string]int32{
		"INTENT_SUCCESS":                          0,
		"INTENT_INVALID_REQUEST":                  4000,
		"INTENT_INVALID_PARAMETERS":               4001,
		"INTENT_MISSING_REQUIRED_FIELD":           4002,
		"INTENT_INVALID_FIELD_FORMAT":             4003,
		"INTENT_INVALID_UUID":                     4004,
		"INTENT_INVALID_ADDRESS":                  4005,
		"INTENT_INVALID_TIMESTAMP":                4006,
		"INTENT_INVALID_SIGNATURE_FORMAT":         4007,
		"INTENT_INVALID_CHAIN_ID":                 4008,
		"INTENT_INVALID_TOKEN_ADDRESS":            4009,
		"INTENT_EXPIRED_DEADLINE":                 4100,
		"INTENT_INVALID_BUDGET":                   4101,
		"INTENT_BUDGET_TOO_LOW":                   4102,
		"INTENT_BUDGET_TOO_HIGH":                  4103,
		"INTENT_DEADLINE_TOO_EARLY":               4104,
		"INTENT_DEADLINE_TOO_LATE":                4105,
		"INTENT_INVALID_INTENT_TYPE":              4106,
		"INTENT_UNSUPPORTED_CHAIN":                4107,
		"INTENT_UNSUPPORTED_TOKEN":                4108,
		"INTENT_PARAMS_TOO_LARGE":                 4109,
		"INTENT_SIGNATURE_VERIFICATION_FAILED":    4200,
		"INTENT_INVALID_SIGNATURE":                4201,
		"INTENT_SIGNATURE_MISMATCH":               4202,
		"INTENT_SIGNER_MISMATCH":                  4203,
		"INTENT_SIGNATURE_REPLAY":                 4204,
		"INTENT_SIGNATURE_EXPIRED":                4205,
		"INTENT_INVALID_SIGNATURE_TYPE":           4206,
		"INTENT_EIP712_VALIDATION_FAILED":         4207,
		"INTENT_EIP191_VALIDATION_FAILED":         4208,
		"INTENT_SUBNET_NOT_FOUND":                 4300,
		"INTENT_SUBNET_INACTIVE":                  4301,
		"INTENT_SUBNET_OVERLOADED":                4302,
		"INTENT_SUBNET_UNSUPPORTED":               4303,
		"INTENT_SUBNET_INSUFFICIENT_VALIDATORS":   4304,
		"INTENT_SUBNET_MAINTENANCE":               4305,
		"INTENT_ALREADY_EXISTS":                   5000,
		"INTENT_NOT_FOUND":                        5001,
		"INTENT_INVALID_STATUS":                   5002,
		"INTENT_STATUS_TRANSITION_INVALID":        5003,
		"INTENT_ALREADY_PROCESSED":                5004,
		"INTENT_ALREADY_EXPIRED":                  5005,
		"INTENT_ALREADY_COMPLETED":                5006,
		"INTENT_ALREADY_FAILED":                   5007,
		"INTENT_CANNOT_CANCEL":                    5008,
		"INTENT_PROCESSING_DEADLINE_PASSED":       5009,
		"INTENT_BIDDING_NOT_STARTED":              5100,
		"INTENT_BIDDING_ENDED":                    5101,
		"INTENT_NO_VALID_BIDS":                    5102,
		"INTENT_BID_TOO_LOW":                      5103,
		"INTENT_BID_TOO_HIGH":                     5104,
		"INTENT_BIDDER_NOT_QUALIFIED":             5105,
		"INTENT_BID_ALREADY_EXISTS":               5106,
		"INTENT_INSUFFICIENT_STAKE":               5107,
		"INTENT_EXECUTION_NOT_STARTED":            5200,
		"INTENT_EXECUTION_FAILED":                 5201,
		"INTENT_EXECUTION_TIMEOUT":                5202,
		"INTENT_EXECUTION_REJECTED":               5203,
		"INTENT_EXECUTION_PARAMS_INVALID":         5204,
		"INTENT_EXECUTION_INSUFFICIENT_GAS":       5205,
		"INTENT_EXECUTION_NETWORK_ERROR":          5206,
		"INTENT_EXECUTION_CONTRACT_ERROR":         5207,
		"INTENT_VALIDATION_PENDING":               5300,
		"INTENT_VALIDATION_FAILED":                5301,
		"INTENT_VALIDATION_TIMEOUT":               5302,
		"INTENT_INSUFFICIENT_VALIDATORS":          5303,
		"INTENT_VALIDATION_CONSENSUS_FAILED":      5304,
		"INTENT_VALIDATION_SIGNATURE_INVALID":     5305,
		"INTENT_RATE_LIMIT_EXCEEDED":              6000,
		"INTENT_QUEUE_FULL":                       6001,
		"INTENT_MAX_CONCURRENT_LIMIT":             6002,
		"INTENT_DAILY_LIMIT_EXCEEDED":             6003,
		"INTENT_USER_QUOTA_EXCEEDED":              6004,
		"INTENT_SUBNET_CAPACITY_EXCEEDED":         6005,
		"INTENT_GLOBAL_CAPACITY_EXCEEDED":         6006,
		"INTENT_RESOURCE_LOCKED":                  6100,
		"INTENT_RESOURCE_BUSY":                    6101,
		"INTENT_DEPENDENCY_CONFLICT":              6102,
		"INTENT_CONCURRENT_MODIFICATION":          6103,
		"INTENT_VERSION_CONFLICT":                 6104,
		"INTENT_DATABASE_ERROR":                   7000,
		"INTENT_DATABASE_CONNECTION_FAILED":       7001,
		"INTENT_DATABASE_TIMEOUT":                 7002,
		"INTENT_DATABASE_CONSTRAINT_VIOLATION":    7003,
		"INTENT_DATABASE_TRANSACTION_FAILED":      7004,
		"INTENT_DATABASE_MIGRATION_ERROR":         7005,
		"INTENT_CACHE_ERROR":                      7100,
		"INTENT_CACHE_CONNECTION_FAILED":          7101,
		"INTENT_CACHE_TIMEOUT":                    7102,
		"INTENT_CACHE_EVICTION_ERROR":             7103,
		"INTENT_BLOCKCHAIN_ERROR":                 7200,
		"INTENT_BLOCKCHAIN_CONNECTION_FAILED":     7201,
		"INTENT_BLOCKCHAIN_TIMEOUT":               7202,
		"INTENT_BLOCKCHAIN_TRANSACTION_FAILED":    7203,
		"INTENT_BLOCKCHAIN_GAS_ESTIMATION_FAILED": 7204,
		"INTENT_BLOCKCHAIN_INSUFFICIENT_BALANCE":  7205,
		"INTENT_BLOCKCHAIN_NONCE_ERROR":           7206,
		"INTENT_BLOCKCHAIN_NETWORK_CONGESTION":    7207,
		"INTENT_GRPC_ERROR":                       7300,
		"INTENT_GRPC_CONNECTION_FAILED":           7301,
		"INTENT_GRPC_TIMEOUT":                     7302,
		"INTENT_GRPC_UNAVAILABLE":                 7303,
		"INTENT_NETWORK_ERROR":                    7304,
		"INTENT_NETWORK_TIMEOUT":                  7305,
		"INTENT_INTERNAL_ERROR":                   7400,
		"INTENT_CONFIGURATION_ERROR":              7401,
		"INTENT_SERVICE_UNAVAILABLE":              7402,
		"INTENT_MEMORY_ERROR":                     7403,
		"INTENT_FILE_SYSTEM_ERROR":                7404,
		"INTENT_SERIALIZATION_ERROR":              7405,
		"INTENT_DESERIALIZATION_ERROR":            7406,
		"INTENT_ENCRYPTION_ERROR":                 7407,
		"INTENT_DECRYPTION_ERROR":                 7408,
		"INTENT_EXTERNAL_SERVICE_ERROR":           7500,
		"INTENT_EXTERNAL_SERVICE_TIMEOUT":         7501,
		"INTENT_EXTERNAL_SERVICE_UNAVAILABLE":     7502,
		"INTENT_API_RATE_LIMITED":                 7503,
		"INTENT_API_AUTHENTICATION_FAILED":        7504,
	}
)

func (x IntentErrorReason) Enum() *IntentErrorReason {
	p := new(IntentErrorReason)
	*p = x
	return p
}

func (x IntentErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_error_reason_proto_enumTypes[0].Descriptor()
}

func (IntentErrorReason) Type() protoreflect.EnumType {
	return &file_error_reason_proto_enumTypes[0]
}

func (x IntentErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentErrorReason.Descriptor instead.
func (IntentErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_error_reason_proto protoreflect.FileDescriptor

const file_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x12error_reason.proto\x12\frootlayer.v1*\xb2\x1e\n" +
	"\x11IntentErrorReason\x12\x12\n" +
	"\x0eINTENT_SUCCESS\x10\x00\x12\x1b\n" +
	"\x16INTENT_INVALID_REQUEST\x10\xa0\x1f\x12\x1e\n" +
	"\x19INTENT_INVALID_PARAMETERS\x10\xa1\x1f\x12\"\n" +
	"\x1dINTENT_MISSING_REQUIRED_FIELD\x10\xa2\x1f\x12 \n" +
	"\x1bINTENT_INVALID_FIELD_FORMAT\x10\xa3\x1f\x12\x18\n" +
	"\x13INTENT_INVALID_UUID\x10\xa4\x1f\x12\x1b\n" +
	"\x16INTENT_INVALID_ADDRESS\x10\xa5\x1f\x12\x1d\n" +
	"\x18INTENT_INVALID_TIMESTAMP\x10\xa6\x1f\x12$\n" +
	"\x1fINTENT_INVALID_SIGNATURE_FORMAT\x10\xa7\x1f\x12\x1c\n" +
	"\x17INTENT_INVALID_CHAIN_ID\x10\xa8\x1f\x12!\n" +
	"\x1cINTENT_INVALID_TOKEN_ADDRESS\x10\xa9\x1f\x12\x1c\n" +
	"\x17INTENT_EXPIRED_DEADLINE\x10\x84 \x12\x1a\n" +
	"\x15INTENT_INVALID_BUDGET\x10\x85 \x12\x1a\n" +
	"\x15INTENT_BUDGET_TOO_LOW\x10\x86 \x12\x1b\n" +
	"\x16INTENT_BUDGET_TOO_HIGH\x10\x87 \x12\x1e\n" +
	"\x19INTENT_DEADLINE_TOO_EARLY\x10\x88 \x12\x1d\n" +
	"\x18INTENT_DEADLINE_TOO_LATE\x10\x89 \x12\x1f\n" +
	"\x1aINTENT_INVALID_INTENT_TYPE\x10\x8a \x12\x1d\n" +
	"\x18INTENT_UNSUPPORTED_CHAIN\x10\x8b \x12\x1d\n" +
	"\x18INTENT_UNSUPPORTED_TOKEN\x10\x8c \x12\x1c\n" +
	"\x17INTENT_PARAMS_TOO_LARGE\x10\x8d \x12)\n" +
	"$INTENT_SIGNATURE_VERIFICATION_FAILED\x10\xe8 \x12\x1d\n" +
	"\x18INTENT_INVALID_SIGNATURE\x10\xe9 \x12\x1e\n" +
	"\x19INTENT_SIGNATURE_MISMATCH\x10\xea \x12\x1b\n" +
	"\x16INTENT_SIGNER_MISMATCH\x10\xeb \x12\x1c\n" +
	"\x17INTENT_SIGNATURE_REPLAY\x10\xec \x12\x1d\n" +
	"\x18INTENT_SIGNATURE_EXPIRED\x10\xed \x12\"\n" +
	"\x1dINTENT_INVALID_SIGNATURE_TYPE\x10\xee \x12$\n" +
	"\x1fINTENT_EIP712_VALIDATION_FAILED\x10\xef \x12$\n" +
	"\x1fINTENT_EIP191_VALIDATION_FAILED\x10\xf0 \x12\x1c\n" +
	"\x17INTENT_SUBNET_NOT_FOUND\x10\xcc!\x12\x1b\n" +
	"\x16INTENT_SUBNET_INACTIVE\x10\xcd!\x12\x1d\n" +
	"\x18INTENT_SUBNET_OVERLOADED\x10\xce!\x12\x1e\n" +
	"\x19INTENT_SUBNET_UNSUPPORTED\x10\xcf!\x12*\n" +
	"%INTENT_SUBNET_INSUFFICIENT_VALIDATORS\x10\xd0!\x12\x1e\n" +
	"\x19INTENT_SUBNET_MAINTENANCE\x10\xd1!\x12\x1a\n" +
	"\x15INTENT_ALREADY_EXISTS\x10\x88'\x12\x15\n" +
	"\x10INTENT_NOT_FOUND\x10\x89'\x12\x1a\n" +
	"\x15INTENT_INVALID_STATUS\x10\x8a'\x12%\n" +
	" INTENT_STATUS_TRANSITION_INVALID\x10\x8b'\x12\x1d\n" +
	"\x18INTENT_ALREADY_PROCESSED\x10\x8c'\x12\x1b\n" +
	"\x16INTENT_ALREADY_EXPIRED\x10\x8d'\x12\x1d\n" +
	"\x18INTENT_ALREADY_COMPLETED\x10\x8e'\x12\x1a\n" +
	"\x15INTENT_ALREADY_FAILED\x10\x8f'\x12\x19\n" +
	"\x14INTENT_CANNOT_CANCEL\x10\x90'\x12&\n" +
	"!INTENT_PROCESSING_DEADLINE_PASSED\x10\x91'\x12\x1f\n" +
	"\x1aINTENT_BIDDING_NOT_STARTED\x10\xec'\x12\x19\n" +
	"\x14INTENT_BIDDING_ENDED\x10\xed'\x12\x19\n" +
	"\x14INTENT_NO_VALID_BIDS\x10\xee'\x12\x17\n" +
	"\x12INTENT_BID_TOO_LOW\x10\xef'\x12\x18\n" +
	"\x13INTENT_BID_TOO_HIGH\x10\xf0'\x12 \n" +
	"\x1bINTENT_BIDDER_NOT_QUALIFIED\x10\xf1'\x12\x1e\n" +
	"\x19INTENT_BID_ALREADY_EXISTS\x10\xf2'\x12\x1e\n" +
	"\x19INTENT_INSUFFICIENT_STAKE\x10\xf3'\x12!\n" +
	"\x1cINTENT_EXECUTION_NOT_STARTED\x10\xd0(\x12\x1c\n" +
	"\x17INTENT_EXECUTION_FAILED\x10\xd1(\x12\x1d\n" +
	"\x18INTENT_EXECUTION_TIMEOUT\x10\xd2(\x12\x1e\n" +
	"\x19INTENT_EXECUTION_REJECTED\x10\xd3(\x12$\n" +
	"\x1fINTENT_EXECUTION_PARAMS_INVALID\x10\xd4(\x12&\n" +
	"!INTENT_EXECUTION_INSUFFICIENT_GAS\x10\xd5(\x12#\n" +
	"\x1eINTENT_EXECUTION_NETWORK_ERROR\x10\xd6(\x12$\n" +
	"\x1fINTENT_EXECUTION_CONTRACT_ERROR\x10\xd7(\x12\x1e\n" +
	"\x19INTENT_VALIDATION_PENDING\x10\xb4)\x12\x1d\n" +
	"\x18INTENT_VALIDATION_FAILED\x10\xb5)\x12\x1e\n" +
	"\x19INTENT_VALIDATION_TIMEOUT\x10\xb6)\x12#\n" +
	"\x1eINTENT_INSUFFICIENT_VALIDATORS\x10\xb7)\x12'\n" +
	"\"INTENT_VALIDATION_CONSENSUS_FAILED\x10\xb8)\x12(\n" +
	"#INTENT_VALIDATION_SIGNATURE_INVALID\x10\xb9)\x12\x1f\n" +
	"\x1aINTENT_RATE_LIMIT_EXCEEDED\x10\xf0.\x12\x16\n" +
	"\x11INTENT_QUEUE_FULL\x10\xf1.\x12 \n" +
	"\x1bINTENT_MAX_CONCURRENT_LIMIT\x10\xf2.\x12 \n" +
	"\x1bINTENT_DAILY_LIMIT_EXCEEDED\x10\xf3.\x12\x1f\n" +
	"\x1aINTENT_USER_QUOTA_EXCEEDED\x10\xf4.\x12$\n" +
	"\x1fINTENT_SUBNET_CAPACITY_EXCEEDED\x10\xf5.\x12$\n" +
	"\x1fINTENT_GLOBAL_CAPACITY_EXCEEDED\x10\xf6.\x12\x1b\n" +
	"\x16INTENT_RESOURCE_LOCKED\x10\xd4/\x12\x19\n" +
	"\x14INTENT_RESOURCE_BUSY\x10\xd5/\x12\x1f\n" +
	"\x1aINTENT_DEPENDENCY_CONFLICT\x10\xd6/\x12#\n" +
	"\x1eINTENT_CONCURRENT_MODIFICATION\x10\xd7/\x12\x1c\n" +
	"\x17INTENT_VERSION_CONFLICT\x10\xd8/\x12\x1a\n" +
	"\x15INTENT_DATABASE_ERROR\x10\xd86\x12&\n" +
	"!INTENT_DATABASE_CONNECTION_FAILED\x10\xd96\x12\x1c\n" +
	"\x17INTENT_DATABASE_TIMEOUT\x10\xda6\x12)\n" +
	"$INTENT_DATABASE_CONSTRAINT_VIOLATION\x10\xdb6\x12'\n" +
	"\"INTENT_DATABASE_TRANSACTION_FAILED\x10\xdc6\x12$\n" +
	"\x1fINTENT_DATABASE_MIGRATION_ERROR\x10\xdd6\x12\x17\n" +
	"\x12INTENT_CACHE_ERROR\x10\xbc7\x12#\n" +
	"\x1eINTENT_CACHE_CONNECTION_FAILED\x10\xbd7\x12\x19\n" +
	"\x14INTENT_CACHE_TIMEOUT\x10\xbe7\x12 \n" +
	"\x1bINTENT_CACHE_EVICTION_ERROR\x10\xbf7\x12\x1c\n" +
	"\x17INTENT_BLOCKCHAIN_ERROR\x10\xa08\x12(\n" +
	"#INTENT_BLOCKCHAIN_CONNECTION_FAILED\x10\xa18\x12\x1e\n" +
	"\x19INTENT_BLOCKCHAIN_TIMEOUT\x10\xa28\x12)\n" +
	"$INTENT_BLOCKCHAIN_TRANSACTION_FAILED\x10\xa38\x12,\n" +
	"'INTENT_BLOCKCHAIN_GAS_ESTIMATION_FAILED\x10\xa48\x12+\n" +
	"&INTENT_BLOCKCHAIN_INSUFFICIENT_BALANCE\x10\xa58\x12\"\n" +
	"\x1dINTENT_BLOCKCHAIN_NONCE_ERROR\x10\xa68\x12)\n" +
	"$INTENT_BLOCKCHAIN_NETWORK_CONGESTION\x10\xa78\x12\x16\n" +
	"\x11INTENT_GRPC_ERROR\x10\x849\x12\"\n" +
	"\x1dINTENT_GRPC_CONNECTION_FAILED\x10\x859\x12\x18\n" +
	"\x13INTENT_GRPC_TIMEOUT\x10\x869\x12\x1c\n" +
	"\x17INTENT_GRPC_UNAVAILABLE\x10\x879\x12\x19\n" +
	"\x14INTENT_NETWORK_ERROR\x10\x889\x12\x1b\n" +
	"\x16INTENT_NETWORK_TIMEOUT\x10\x899\x12\x1a\n" +
	"\x15INTENT_INTERNAL_ERROR\x10\xe89\x12\x1f\n" +
	"\x1aINTENT_CONFIGURATION_ERROR\x10\xe99\x12\x1f\n" +
	"\x1aINTENT_SERVICE_UNAVAILABLE\x10\xea9\x12\x18\n" +
	"\x13INTENT_MEMORY_ERROR\x10\xeb9\x12\x1d\n" +
	"\x18INTENT_FILE_SYSTEM_ERROR\x10\xec9\x12\x1f\n" +
	"\x1aINTENT_SERIALIZATION_ERROR\x10\xed9\x12!\n" +
	"\x1cINTENT_DESERIALIZATION_ERROR\x10\xee9\x12\x1c\n" +
	"\x17INTENT_ENCRYPTION_ERROR\x10\xef9\x12\x1c\n" +
	"\x17INTENT_DECRYPTION_ERROR\x10\xf09\x12\"\n" +
	"\x1dINTENT_EXTERNAL_SERVICE_ERROR\x10\xcc:\x12$\n" +
	"\x1fINTENT_EXTERNAL_SERVICE_TIMEOUT\x10\xcd:\x12(\n" +
	"#INTENT_EXTERNAL_SERVICE_UNAVAILABLE\x10\xce:\x12\x1c\n" +
	"\x17INTENT_API_RATE_LIMITED\x10\xcf:\x12%\n" +
	" INTENT_API_AUTHENTICATION_FAILED\x10\xd0:BBZ@github.com/PIN-AI/pin-protocol-proto/rootlayer/proto;rootlayerv1b\x06proto3"

var (
	file_error_reason_proto_rawDescOnce sync.Once
	file_error_reason_proto_rawDescData []byte
)

func file_error_reason_proto_rawDescGZIP() []byte {
	file_error_reason_proto_rawDescOnce.Do(func() {
		file_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_reason_proto_rawDesc), len(file_error_reason_proto_rawDesc)))
	})
	return file_error_reason_proto_rawDescData
}

var file_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_reason_proto_goTypes = []any{
	(IntentErrorReason)(0), // 0: rootlayer.v1.IntentErrorReason
}
var file_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_reason_proto_init() }
func file_error_reason_proto_init() {
	if File_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_reason_proto_rawDesc), len(file_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_reason_proto_goTypes,
		DependencyIndexes: file_error_reason_proto_depIdxs,
		EnumInfos:         file_error_reason_proto_enumTypes,
	}.Build()
	File_error_reason_proto = out.File
	file_error_reason_proto_goTypes = nil
	file_error_reason_proto_depIdxs = nil
}
