// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.29.3
// source: rootlayer/service.proto

package rootlayerv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIntentPoolServiceGetIntent = "/rootlayer.v1.IntentPoolService/GetIntent"
const OperationIntentPoolServiceGetIntents = "/rootlayer.v1.IntentPoolService/GetIntents"
const OperationIntentPoolServicePostAssignment = "/rootlayer.v1.IntentPoolService/PostAssignment"
const OperationIntentPoolServicePostAssignmentBatch = "/rootlayer.v1.IntentPoolService/PostAssignmentBatch"
const OperationIntentPoolServicePostAssignments = "/rootlayer.v1.IntentPoolService/PostAssignments"
const OperationIntentPoolServiceSubmitIntent = "/rootlayer.v1.IntentPoolService/SubmitIntent"
const OperationIntentPoolServiceSubmitIntentBatch = "/rootlayer.v1.IntentPoolService/SubmitIntentBatch"
const OperationIntentPoolServiceSubmitValidationBundle = "/rootlayer.v1.IntentPoolService/SubmitValidationBundle"
const OperationIntentPoolServiceSubmitValidationBundleBatch = "/rootlayer.v1.IntentPoolService/SubmitValidationBundleBatch"

type IntentPoolServiceHTTPServer interface {
	// GetIntent Fetch a single intent by its ID.
	GetIntent(context.Context, *GetIntentRequest) (*Intent, error)
	// GetIntents Query intents using multiple filters with pagination.
	GetIntents(context.Context, *GetIntentsRequest) (*GetIntentsResponse, error)
	// PostAssignment Post a single assignment from a subnet matcher.
	//
	// Example request body:
	// {
	//   "assignmentId": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", // bytes32 hex
	//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d", // bytes32 hex
	//   "agentId": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",                         // address (EIP-55 tolerated)
	//   "bidId": "0x0000000000000000000000000000000000000000000000000000000000000000",   // bytes32 hex
	//   "status": 1, // 1=ACTIVE, 2=FAILED
	//   "matcherId": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266",                          // address
	//   "signature": "0x..65-bytes-signature.."                                                // EIP-191 signature
	// }
	PostAssignment(context.Context, *Assignment) (*Ack, error)
	// PostAssignmentBatch Post a batch of assignments from a subnet matcher.
	PostAssignmentBatch(context.Context, *AssignmentBatch) (*Ack, error)
	// PostAssignments Deprecated alias for backward compatibility.
	PostAssignments(context.Context, *AssignmentBatch) (*Ack, error)
	// SubmitIntent Submit a new intent into the RootLayer mempool.
	//
	// Body is a SubmitIntentRequest. The signature proves ownership of
	// the requester address and integrity of parameters.
	//
	// Example request body:
	// {
	//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d",
	//   "subnetId": "0x0000000000000000000000000000000000000000000000000000000000000001",
	//   "requester": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",
	//   "settleChain": "base_sepolia",
	//   "intentType": "test",
	//   "params": {
	//     "intentRaw": "cGluZ3Jhdw==",
	//     "metadata": "LXRlc3QgbWV0YS0="
	//   },
	//   "tipsToken": "0x0000000000000000000000000000000000000000",
	//   "tips": "0",
	//   "deadline": "1822275330",
	//   "signature": "cfe0c61b6c01fb6b907fd11e550797c761b2cecbc7a3d59e8775fe8640b88c5f1f297f7fdb321c3d1122",
	//   "budgetToken": "0x0000000000000000000000000000000000000000",
	//   "budget": "0"
	// }
	SubmitIntent(context.Context, *SubmitIntentRequest) (*SubmitIntentResponse, error)
	// SubmitIntentBatch Submit a batch of intents.
	SubmitIntentBatch(context.Context, *SubmitIntentBatchRequest) (*SubmitIntentBatchResponse, error)
	// SubmitValidationBundle Submit an aggregated ValidationBundle from subnet validators.
	//
	// Example request body:
	// {
	//   "subnetId": "0x0000000000000000000000000000000000000000000000000000000000000001",  // bytes32 hex
	//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d",  // bytes32 hex
	//   "assignmentId": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", // bytes32 hex
	//   "agentId": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",                           // address
	//   "rootHeight": "1",
	//   "rootHash": "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", // bytes32 hex
	//   "executedAt": "1",
	//   "resultHash": "0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", // bytes32 hex
	//   "proofHash": "0xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",  // bytes32 hex
	//   "signatures": [
	//     { "validator": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266", "signature": "0x..65-bytes.." }
	//   ],
	//   "signerBitmap": "0x01",
	//   "totalWeight": "1",
	//   "aggregatorId": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266",
	//   "completedAt": "1822275330"
	// }
	SubmitValidationBundle(context.Context, *ValidationBundle) (*ValidationAck, error)
	// SubmitValidationBundleBatch Submit a batch of validation bundles.
	SubmitValidationBundleBatch(context.Context, *ValidationBundleBatchRequest) (*ValidationBundleBatchResponse, error)
}

func RegisterIntentPoolServiceHTTPServer(s *http.Server, srv IntentPoolServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/intents/submit/batch", _IntentPoolService_SubmitIntentBatch0_HTTP_Handler(srv))
	r.POST("/api/v1/intents/submit", _IntentPoolService_SubmitIntent0_HTTP_Handler(srv))
	r.GET("/api/v1/intents/query", _IntentPoolService_GetIntents0_HTTP_Handler(srv))
	r.GET("/api/v1/intents/query/{intent_id}", _IntentPoolService_GetIntent0_HTTP_Handler(srv))
	r.POST("/api/v1/callbacks/assignment/submit", _IntentPoolService_PostAssignment0_HTTP_Handler(srv))
	r.POST("/api/v1/callbacks/assignments/submit", _IntentPoolService_PostAssignmentBatch0_HTTP_Handler(srv))
	r.POST("/api/v1/callbacks/assignments/submit", _IntentPoolService_PostAssignments0_HTTP_Handler(srv))
	r.POST("/api/v1/callbacks/validation/submit", _IntentPoolService_SubmitValidationBundle0_HTTP_Handler(srv))
	r.POST("/api/v1/callbacks/validation/submit/batch", _IntentPoolService_SubmitValidationBundleBatch0_HTTP_Handler(srv))
}

func _IntentPoolService_SubmitIntentBatch0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitIntentBatchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServiceSubmitIntentBatch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitIntentBatch(ctx, req.(*SubmitIntentBatchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitIntentBatchResponse)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_SubmitIntent0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitIntentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServiceSubmitIntent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitIntent(ctx, req.(*SubmitIntentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitIntentResponse)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_GetIntents0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetIntentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServiceGetIntents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetIntents(ctx, req.(*GetIntentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetIntentsResponse)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_GetIntent0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetIntentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServiceGetIntent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetIntent(ctx, req.(*GetIntentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Intent)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_PostAssignment0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Assignment
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServicePostAssignment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostAssignment(ctx, req.(*Assignment))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Ack)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_PostAssignmentBatch0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignmentBatch
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServicePostAssignmentBatch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostAssignmentBatch(ctx, req.(*AssignmentBatch))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Ack)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_PostAssignments0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignmentBatch
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServicePostAssignments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostAssignments(ctx, req.(*AssignmentBatch))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Ack)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_SubmitValidationBundle0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidationBundle
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServiceSubmitValidationBundle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitValidationBundle(ctx, req.(*ValidationBundle))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidationAck)
		return ctx.Result(200, reply)
	}
}

func _IntentPoolService_SubmitValidationBundleBatch0_HTTP_Handler(srv IntentPoolServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidationBundleBatchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIntentPoolServiceSubmitValidationBundleBatch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitValidationBundleBatch(ctx, req.(*ValidationBundleBatchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidationBundleBatchResponse)
		return ctx.Result(200, reply)
	}
}

type IntentPoolServiceHTTPClient interface {
	// GetIntent Fetch a single intent by its ID.
	GetIntent(ctx context.Context, req *GetIntentRequest, opts ...http.CallOption) (rsp *Intent, err error)
	// GetIntents Query intents using multiple filters with pagination.
	GetIntents(ctx context.Context, req *GetIntentsRequest, opts ...http.CallOption) (rsp *GetIntentsResponse, err error)
	// PostAssignment Post a single assignment from a subnet matcher.
	//
	// Example request body:
	// {
	//   "assignmentId": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", // bytes32 hex
	//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d", // bytes32 hex
	//   "agentId": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",                         // address (EIP-55 tolerated)
	//   "bidId": "0x0000000000000000000000000000000000000000000000000000000000000000",   // bytes32 hex
	//   "status": 1, // 1=ACTIVE, 2=FAILED
	//   "matcherId": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266",                          // address
	//   "signature": "0x..65-bytes-signature.."                                                // EIP-191 signature
	// }
	PostAssignment(ctx context.Context, req *Assignment, opts ...http.CallOption) (rsp *Ack, err error)
	// PostAssignmentBatch Post a batch of assignments from a subnet matcher.
	PostAssignmentBatch(ctx context.Context, req *AssignmentBatch, opts ...http.CallOption) (rsp *Ack, err error)
	// PostAssignments Deprecated alias for backward compatibility.
	PostAssignments(ctx context.Context, req *AssignmentBatch, opts ...http.CallOption) (rsp *Ack, err error)
	// SubmitIntent Submit a new intent into the RootLayer mempool.
	//
	// Body is a SubmitIntentRequest. The signature proves ownership of
	// the requester address and integrity of parameters.
	//
	// Example request body:
	// {
	//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d",
	//   "subnetId": "0x0000000000000000000000000000000000000000000000000000000000000001",
	//   "requester": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",
	//   "settleChain": "base_sepolia",
	//   "intentType": "test",
	//   "params": {
	//     "intentRaw": "cGluZ3Jhdw==",
	//     "metadata": "LXRlc3QgbWV0YS0="
	//   },
	//   "tipsToken": "0x0000000000000000000000000000000000000000",
	//   "tips": "0",
	//   "deadline": "1822275330",
	//   "signature": "cfe0c61b6c01fb6b907fd11e550797c761b2cecbc7a3d59e8775fe8640b88c5f1f297f7fdb321c3d1122",
	//   "budgetToken": "0x0000000000000000000000000000000000000000",
	//   "budget": "0"
	// }
	SubmitIntent(ctx context.Context, req *SubmitIntentRequest, opts ...http.CallOption) (rsp *SubmitIntentResponse, err error)
	// SubmitIntentBatch Submit a batch of intents.
	SubmitIntentBatch(ctx context.Context, req *SubmitIntentBatchRequest, opts ...http.CallOption) (rsp *SubmitIntentBatchResponse, err error)
	// SubmitValidationBundle Submit an aggregated ValidationBundle from subnet validators.
	//
	// Example request body:
	// {
	//   "subnetId": "0x0000000000000000000000000000000000000000000000000000000000000001",  // bytes32 hex
	//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d",  // bytes32 hex
	//   "assignmentId": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", // bytes32 hex
	//   "agentId": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",                           // address
	//   "rootHeight": "1",
	//   "rootHash": "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", // bytes32 hex
	//   "executedAt": "1",
	//   "resultHash": "0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", // bytes32 hex
	//   "proofHash": "0xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",  // bytes32 hex
	//   "signatures": [
	//     { "validator": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266", "signature": "0x..65-bytes.." }
	//   ],
	//   "signerBitmap": "0x01",
	//   "totalWeight": "1",
	//   "aggregatorId": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266",
	//   "completedAt": "1822275330"
	// }
	SubmitValidationBundle(ctx context.Context, req *ValidationBundle, opts ...http.CallOption) (rsp *ValidationAck, err error)
	// SubmitValidationBundleBatch Submit a batch of validation bundles.
	SubmitValidationBundleBatch(ctx context.Context, req *ValidationBundleBatchRequest, opts ...http.CallOption) (rsp *ValidationBundleBatchResponse, err error)
}

type IntentPoolServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewIntentPoolServiceHTTPClient(client *http.Client) IntentPoolServiceHTTPClient {
	return &IntentPoolServiceHTTPClientImpl{client}
}

// GetIntent Fetch a single intent by its ID.
func (c *IntentPoolServiceHTTPClientImpl) GetIntent(ctx context.Context, in *GetIntentRequest, opts ...http.CallOption) (*Intent, error) {
	var out Intent
	pattern := "/api/v1/intents/query/{intent_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIntentPoolServiceGetIntent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetIntents Query intents using multiple filters with pagination.
func (c *IntentPoolServiceHTTPClientImpl) GetIntents(ctx context.Context, in *GetIntentsRequest, opts ...http.CallOption) (*GetIntentsResponse, error) {
	var out GetIntentsResponse
	pattern := "/api/v1/intents/query"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIntentPoolServiceGetIntents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PostAssignment Post a single assignment from a subnet matcher.
//
// Example request body:
// {
//   "assignmentId": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", // bytes32 hex
//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d", // bytes32 hex
//   "agentId": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",                         // address (EIP-55 tolerated)
//   "bidId": "0x0000000000000000000000000000000000000000000000000000000000000000",   // bytes32 hex
//   "status": 1, // 1=ACTIVE, 2=FAILED
//   "matcherId": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266",                          // address
//   "signature": "0x..65-bytes-signature.."                                                // EIP-191 signature
// }
func (c *IntentPoolServiceHTTPClientImpl) PostAssignment(ctx context.Context, in *Assignment, opts ...http.CallOption) (*Ack, error) {
	var out Ack
	pattern := "/api/v1/callbacks/assignment/submit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIntentPoolServicePostAssignment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PostAssignmentBatch Post a batch of assignments from a subnet matcher.
func (c *IntentPoolServiceHTTPClientImpl) PostAssignmentBatch(ctx context.Context, in *AssignmentBatch, opts ...http.CallOption) (*Ack, error) {
	var out Ack
	pattern := "/api/v1/callbacks/assignments/submit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIntentPoolServicePostAssignmentBatch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PostAssignments Deprecated alias for backward compatibility.
func (c *IntentPoolServiceHTTPClientImpl) PostAssignments(ctx context.Context, in *AssignmentBatch, opts ...http.CallOption) (*Ack, error) {
	var out Ack
	pattern := "/api/v1/callbacks/assignments/submit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIntentPoolServicePostAssignments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitIntent Submit a new intent into the RootLayer mempool.
//
// Body is a SubmitIntentRequest. The signature proves ownership of
// the requester address and integrity of parameters.
//
// Example request body:
// {
//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d",
//   "subnetId": "0x0000000000000000000000000000000000000000000000000000000000000001",
//   "requester": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",
//   "settleChain": "base_sepolia",
//   "intentType": "test",
//   "params": {
//     "intentRaw": "cGluZ3Jhdw==",
//     "metadata": "LXRlc3QgbWV0YS0="
//   },
//   "tipsToken": "0x0000000000000000000000000000000000000000",
//   "tips": "0",
//   "deadline": "1822275330",
//   "signature": "cfe0c61b6c01fb6b907fd11e550797c761b2cecbc7a3d59e8775fe8640b88c5f1f297f7fdb321c3d1122",
//   "budgetToken": "0x0000000000000000000000000000000000000000",
//   "budget": "0"
// }
func (c *IntentPoolServiceHTTPClientImpl) SubmitIntent(ctx context.Context, in *SubmitIntentRequest, opts ...http.CallOption) (*SubmitIntentResponse, error) {
	var out SubmitIntentResponse
	pattern := "/api/v1/intents/submit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIntentPoolServiceSubmitIntent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitIntentBatch Submit a batch of intents.
func (c *IntentPoolServiceHTTPClientImpl) SubmitIntentBatch(ctx context.Context, in *SubmitIntentBatchRequest, opts ...http.CallOption) (*SubmitIntentBatchResponse, error) {
	var out SubmitIntentBatchResponse
	pattern := "/api/v1/intents/submit/batch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIntentPoolServiceSubmitIntentBatch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitValidationBundle Submit an aggregated ValidationBundle from subnet validators.
//
// Example request body:
// {
//   "subnetId": "0x0000000000000000000000000000000000000000000000000000000000000001",  // bytes32 hex
//   "intentId": "0xb7c98798a6ec454427a60cff94b54276fe82396f714c02499a40c8f3f6325f8d",  // bytes32 hex
//   "assignmentId": "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", // bytes32 hex
//   "agentId": "0x9290085Cd66bD1A3C7D277EF7DBcbD2e98457b6f",                           // address
//   "rootHeight": "1",
//   "rootHash": "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", // bytes32 hex
//   "executedAt": "1",
//   "resultHash": "0xcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", // bytes32 hex
//   "proofHash": "0xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",  // bytes32 hex
//   "signatures": [
//     { "validator": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266", "signature": "0x..65-bytes.." }
//   ],
//   "signerBitmap": "0x01",
//   "totalWeight": "1",
//   "aggregatorId": "0xF39fd6e51aad88F6F4ce6aB8827279cffFb92266",
//   "completedAt": "1822275330"
// }
func (c *IntentPoolServiceHTTPClientImpl) SubmitValidationBundle(ctx context.Context, in *ValidationBundle, opts ...http.CallOption) (*ValidationAck, error) {
	var out ValidationAck
	pattern := "/api/v1/callbacks/validation/submit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIntentPoolServiceSubmitValidationBundle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitValidationBundleBatch Submit a batch of validation bundles.
func (c *IntentPoolServiceHTTPClientImpl) SubmitValidationBundleBatch(ctx context.Context, in *ValidationBundleBatchRequest, opts ...http.CallOption) (*ValidationBundleBatchResponse, error) {
	var out ValidationBundleBatchResponse
	pattern := "/api/v1/callbacks/validation/submit/batch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIntentPoolServiceSubmitValidationBundleBatch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationHealthServiceCheck = "/rootlayer.v1.HealthService/Check"

type HealthServiceHTTPServer interface {
	Check(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
}

func RegisterHealthServiceHTTPServer(s *http.Server, srv HealthServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/health", _HealthService_Check0_HTTP_Handler(srv))
}

func _HealthService_Check0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Check(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthCheckResponse)
		return ctx.Result(200, reply)
	}
}

type HealthServiceHTTPClient interface {
	Check(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *HealthCheckResponse, err error)
}

type HealthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthServiceHTTPClient(client *http.Client) HealthServiceHTTPClient {
	return &HealthServiceHTTPClientImpl{client}
}

func (c *HealthServiceHTTPClientImpl) Check(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*HealthCheckResponse, error) {
	var out HealthCheckResponse
	pattern := "/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthServiceCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationRelayerServiceHeartbeat = "/rootlayer.v1.RelayerService/Heartbeat"
const OperationRelayerServiceSubmitDirectResult = "/rootlayer.v1.RelayerService/SubmitDirectResult"

type RelayerServiceHTTPServer interface {
	// Heartbeat Heartbeat keeps the Agent connection alive
	Heartbeat(context.Context, *HeartbeatRequest) (*emptypb.Empty, error)
	// SubmitDirectResult SubmitDirectResult allows Agent to submit execution results
	SubmitDirectResult(context.Context, *DirectResultRequest) (*DirectResultResponse, error)
}

func RegisterRelayerServiceHTTPServer(s *http.Server, srv RelayerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/direct/results", _RelayerService_SubmitDirectResult0_HTTP_Handler(srv))
	r.POST("/v1/direct/heartbeat", _RelayerService_Heartbeat0_HTTP_Handler(srv))
}

func _RelayerService_SubmitDirectResult0_HTTP_Handler(srv RelayerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DirectResultRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRelayerServiceSubmitDirectResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitDirectResult(ctx, req.(*DirectResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DirectResultResponse)
		return ctx.Result(200, reply)
	}
}

func _RelayerService_Heartbeat0_HTTP_Handler(srv RelayerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HeartbeatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRelayerServiceHeartbeat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Heartbeat(ctx, req.(*HeartbeatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type RelayerServiceHTTPClient interface {
	// Heartbeat Heartbeat keeps the Agent connection alive
	Heartbeat(ctx context.Context, req *HeartbeatRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// SubmitDirectResult SubmitDirectResult allows Agent to submit execution results
	SubmitDirectResult(ctx context.Context, req *DirectResultRequest, opts ...http.CallOption) (rsp *DirectResultResponse, err error)
}

type RelayerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRelayerServiceHTTPClient(client *http.Client) RelayerServiceHTTPClient {
	return &RelayerServiceHTTPClientImpl{client}
}

// Heartbeat Heartbeat keeps the Agent connection alive
func (c *RelayerServiceHTTPClientImpl) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/direct/heartbeat"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRelayerServiceHeartbeat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitDirectResult SubmitDirectResult allows Agent to submit execution results
func (c *RelayerServiceHTTPClientImpl) SubmitDirectResult(ctx context.Context, in *DirectResultRequest, opts ...http.CallOption) (*DirectResultResponse, error) {
	var out DirectResultResponse
	pattern := "/v1/direct/results"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRelayerServiceSubmitDirectResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationDirectIntentServiceGetDirectResult = "/rootlayer.v1.DirectIntentService/GetDirectResult"
const OperationDirectIntentServiceSubmitDirectIntent = "/rootlayer.v1.DirectIntentService/SubmitDirectIntent"

type DirectIntentServiceHTTPServer interface {
	// GetDirectResult GetDirectResult queries the execution result of a Direct Intent
	GetDirectResult(context.Context, *GetDirectResultRequest) (*DirectResultDetail, error)
	// SubmitDirectIntent SubmitDirectIntent submits a Direct Intent and waits for Agent response
	// Supports hybrid sync/async mode: returns result within timeout, or returns intent_id for async query
	SubmitDirectIntent(context.Context, *SubmitDirectIntentRequest) (*SubmitDirectIntentResponse, error)
}

func RegisterDirectIntentServiceHTTPServer(s *http.Server, srv DirectIntentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/direct/intents", _DirectIntentService_SubmitDirectIntent0_HTTP_Handler(srv))
	r.GET("/v1/direct/intents/{intent_id}/result", _DirectIntentService_GetDirectResult0_HTTP_Handler(srv))
}

func _DirectIntentService_SubmitDirectIntent0_HTTP_Handler(srv DirectIntentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitDirectIntentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDirectIntentServiceSubmitDirectIntent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitDirectIntent(ctx, req.(*SubmitDirectIntentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitDirectIntentResponse)
		return ctx.Result(200, reply)
	}
}

func _DirectIntentService_GetDirectResult0_HTTP_Handler(srv DirectIntentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDirectResultRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDirectIntentServiceGetDirectResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDirectResult(ctx, req.(*GetDirectResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DirectResultDetail)
		return ctx.Result(200, reply)
	}
}

type DirectIntentServiceHTTPClient interface {
	// GetDirectResult GetDirectResult queries the execution result of a Direct Intent
	GetDirectResult(ctx context.Context, req *GetDirectResultRequest, opts ...http.CallOption) (rsp *DirectResultDetail, err error)
	// SubmitDirectIntent SubmitDirectIntent submits a Direct Intent and waits for Agent response
	// Supports hybrid sync/async mode: returns result within timeout, or returns intent_id for async query
	SubmitDirectIntent(ctx context.Context, req *SubmitDirectIntentRequest, opts ...http.CallOption) (rsp *SubmitDirectIntentResponse, err error)
}

type DirectIntentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDirectIntentServiceHTTPClient(client *http.Client) DirectIntentServiceHTTPClient {
	return &DirectIntentServiceHTTPClientImpl{client}
}

// GetDirectResult GetDirectResult queries the execution result of a Direct Intent
func (c *DirectIntentServiceHTTPClientImpl) GetDirectResult(ctx context.Context, in *GetDirectResultRequest, opts ...http.CallOption) (*DirectResultDetail, error) {
	var out DirectResultDetail
	pattern := "/v1/direct/intents/{intent_id}/result"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDirectIntentServiceGetDirectResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitDirectIntent SubmitDirectIntent submits a Direct Intent and waits for Agent response
// Supports hybrid sync/async mode: returns result within timeout, or returns intent_id for async query
func (c *DirectIntentServiceHTTPClientImpl) SubmitDirectIntent(ctx context.Context, in *SubmitDirectIntentRequest, opts ...http.CallOption) (*SubmitDirectIntentResponse, error) {
	var out SubmitDirectIntentResponse
	pattern := "/v1/direct/intents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDirectIntentServiceSubmitDirectIntent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
